[package]
name = "solve_arrow_puzzle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
clap = { version = "*", features = ["derive"] }
itertools = "*"
phf = { version = "*", features = ["macros"] }
proptest = "*"
rand = "*"
thiserror = "*"
