use crate::puzzle::RowPoke;

pub const SOLUTIONS: [&[RowPoke]; 256] = [
    &[],
    &[RowPoke::C],
    &[RowPoke::C, RowPoke::C],
    &[RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::C, RowPoke::C, RowPoke::C, RowPoke::D],
    &[RowPoke::D],
    &[RowPoke::C, RowPoke::D],
    &[RowPoke::C, RowPoke::C, RowPoke::D],
    &[RowPoke::A, RowPoke::A, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::A, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::A],
    &[RowPoke::A, RowPoke::A, RowPoke::C],
    &[RowPoke::A, RowPoke::C],
    &[RowPoke::A, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::A],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::B],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C],
    &[
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
    ],
    &[
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::B, RowPoke::B, RowPoke::B],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::D,
    ],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
        RowPoke::D,
    ],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::D],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::D],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
    ],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
    ],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::B],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::B],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::C],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
    ],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::B, RowPoke::B],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::C],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::B, RowPoke::B],
    &[RowPoke::B, RowPoke::B, RowPoke::C],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::D],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::D],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
        RowPoke::D,
    ],
    &[RowPoke::B, RowPoke::B, RowPoke::D],
    &[RowPoke::B, RowPoke::D],
    &[RowPoke::B, RowPoke::C, RowPoke::D],
    &[RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::D],
    &[RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C, RowPoke::D],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::A, RowPoke::B],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::C],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::B, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::B],
    &[RowPoke::A, RowPoke::B, RowPoke::C],
    &[RowPoke::B, RowPoke::C],
    &[RowPoke::B, RowPoke::C, RowPoke::C],
    &[RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::B],
    &[RowPoke::B],
    &[RowPoke::B, RowPoke::C],
    &[RowPoke::B, RowPoke::C, RowPoke::C],
    &[RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C, RowPoke::D],
    &[RowPoke::B, RowPoke::D],
    &[RowPoke::B, RowPoke::C, RowPoke::D],
    &[RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::D],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::C, RowPoke::C],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::A, RowPoke::B],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::C],
    &[RowPoke::A, RowPoke::B, RowPoke::C],
    &[RowPoke::A, RowPoke::B, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::B],
    &[RowPoke::A],
    &[RowPoke::A, RowPoke::C],
    &[RowPoke::A, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::C, RowPoke::C, RowPoke::C],
    &[],
    &[RowPoke::C],
    &[RowPoke::C, RowPoke::C],
    &[RowPoke::C, RowPoke::C, RowPoke::D],
    &[RowPoke::C, RowPoke::C, RowPoke::C, RowPoke::D],
    &[RowPoke::D],
    &[RowPoke::C, RowPoke::D],
    &[RowPoke::A, RowPoke::A, RowPoke::C],
    &[RowPoke::A, RowPoke::A, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::A, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::A],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::B],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
    ],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
    ],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::B],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C],
    &[
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::B, RowPoke::B, RowPoke::B],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::D],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::D,
    ],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
        RowPoke::D,
    ],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::D],
    &[RowPoke::B, RowPoke::B, RowPoke::D],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::D],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::D],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
        RowPoke::D,
    ],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::B],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::C],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C],
    &[
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::B, RowPoke::B],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::C],
    &[RowPoke::B, RowPoke::B, RowPoke::C],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::B, RowPoke::B],
    &[RowPoke::B, RowPoke::B],
    &[RowPoke::B, RowPoke::B, RowPoke::C],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
        RowPoke::D,
    ],
    &[RowPoke::B, RowPoke::B, RowPoke::D],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::D],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::D],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
    ],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::B],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::C],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::C],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C],
    &[
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::B, RowPoke::B],
    &[RowPoke::A, RowPoke::B],
    &[RowPoke::A, RowPoke::B, RowPoke::C],
    &[RowPoke::A, RowPoke::B, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::B],
    &[RowPoke::B, RowPoke::C],
    &[RowPoke::B, RowPoke::C, RowPoke::C],
    &[RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::D],
    &[RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C, RowPoke::D],
    &[RowPoke::B, RowPoke::D],
    &[RowPoke::B, RowPoke::C, RowPoke::D],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::C],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::C, RowPoke::C],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::A, RowPoke::B],
    &[RowPoke::A, RowPoke::A],
    &[RowPoke::A, RowPoke::A, RowPoke::C],
    &[RowPoke::A, RowPoke::A, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::A, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::A],
    &[RowPoke::A, RowPoke::C],
    &[RowPoke::A, RowPoke::C, RowPoke::C],
    &[RowPoke::C, RowPoke::C],
    &[RowPoke::C, RowPoke::C, RowPoke::C],
    &[],
    &[RowPoke::C],
    &[RowPoke::C, RowPoke::D],
    &[RowPoke::C, RowPoke::C, RowPoke::D],
    &[RowPoke::C, RowPoke::C, RowPoke::C, RowPoke::D],
    &[RowPoke::D],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::D],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::D],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::D,
    ],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
        RowPoke::D,
    ],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::B],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
    ],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
    ],
    &[
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
    ],
    &[
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::B],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::B, RowPoke::B, RowPoke::B],
    &[RowPoke::B, RowPoke::B, RowPoke::B],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
        RowPoke::D,
    ],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::D],
    &[RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::D],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::D,
    ],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
    ],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::B],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::B, RowPoke::C],
    &[
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
    ],
    &[
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::B],
    &[RowPoke::A, RowPoke::B, RowPoke::B],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::C],
    &[RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C],
    &[
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::B, RowPoke::B],
    &[RowPoke::B, RowPoke::B, RowPoke::C],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::D],
    &[
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
        RowPoke::D,
    ],
    &[RowPoke::B, RowPoke::B, RowPoke::D],
    &[RowPoke::B, RowPoke::B, RowPoke::C, RowPoke::D],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::B, RowPoke::C],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
    ],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::B],
    &[RowPoke::A, RowPoke::A, RowPoke::B],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::C],
    &[RowPoke::A, RowPoke::A, RowPoke::B, RowPoke::C, RowPoke::C],
    &[
        RowPoke::A,
        RowPoke::A,
        RowPoke::B,
        RowPoke::C,
        RowPoke::C,
        RowPoke::C,
    ],
    &[RowPoke::A, RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::B],
    &[RowPoke::A, RowPoke::B, RowPoke::C],
    &[RowPoke::A, RowPoke::B, RowPoke::C, RowPoke::C],
    &[RowPoke::B, RowPoke::C, RowPoke::C],
    &[RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::B],
    &[RowPoke::B, RowPoke::C],
    &[RowPoke::B, RowPoke::C, RowPoke::D],
    &[RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::D],
    &[RowPoke::B, RowPoke::C, RowPoke::C, RowPoke::C, RowPoke::D],
    &[RowPoke::B, RowPoke::D],
    &[RowPoke::D],
    &[RowPoke::C, RowPoke::D],
    &[RowPoke::C, RowPoke::C, RowPoke::D],
    &[RowPoke::C, RowPoke::C, RowPoke::C, RowPoke::D],
    &[RowPoke::A, RowPoke::A, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::A],
    &[RowPoke::A, RowPoke::A, RowPoke::C],
    &[RowPoke::A, RowPoke::A, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::C, RowPoke::C],
    &[RowPoke::A, RowPoke::C, RowPoke::C, RowPoke::C],
    &[RowPoke::A],
    &[RowPoke::A, RowPoke::C],
    &[RowPoke::C],
    &[RowPoke::C, RowPoke::C],
    &[RowPoke::C, RowPoke::C, RowPoke::C],
    &[],
];
